#!/bin/sh
export PIPESTATUS_PIPE="/tmp/testbar"
export MODULE_PATH="./modules"
TEMPLATE="${TEMPLATE} <CPU>  <MEM> <NET_SPEED>  <LIGHT> <VOL_SYM> <VOL> <BAT>"
TEMPLATE="${TEMPLATE}  <TIME>"

pipestatus -t "$TEMPLATE" -f "/tmp/testbar"
# echo "CPU:cccppppppuuuuu!!!!!" > /tmp/testbar
