#!/bin/sh
echo "PLAYERCTL:"
 playerctl -i chromium,kdeconnect.mpris -F metadata --format '{{playerName}}: {{title}} [{{duration(position)}}/{{duration(mpris:length)}}]' | while read -r data; do
        echo "PLAYERCTL:$data"
done
