#!/bin/sh
echo "PLAYERCTL:"
 playerctl -i chromium,kdeconnect.mpris -F metadata --format '{{status}} {{playerName}}: {{title}} [{{duration(position)}}/{{duration(mpris:length)}}]' | while read -r data; do
        if [ "${data#Playing}" != "$data" ]; then
                data=" ${data#Playing}"
        elif [ "${data#Paused}" != "$data" ]; then
                data=" ${data#Paused}"
        else
                data="${data#* }"
        fi
        echo "PLAYERCTL:$data"
done
