#!/bin/sh
ps_PULSE() {
  sinks="$(pactl list sinks)"
  bt_bat="$(pactl list cards | grep "bluetooth.battery" | grep -o '[[:digit:]]*%')"
  [ "${sinks#*Active Port:*-speaker}" != "$sinks" ] && echo "VOL_SYM:🔈"
  [ "${sinks#*Active Port:*-headphone}" != "$sinks" ] && echo "VOL_SYM:🎧"
  [ "${sinks#*Active Port: headset-output}" != "$sinks" ] && echo "VOL_SYM:🎧[$bt_bat]"

  vol="${sinks%%%*}"; vol="${vol##* }"; echo "VOL:$vol"
  pactl subscribe | while read -r event; do
          [ "${event#*client}" != "$event" ] && continue
          sinks="$(pactl list sinks)"
          [ "${event#*\'change\' on card}" != "$event" ] && {
                  bt_bat="$(pactl list cards | grep "bluetooth.battery" | grep -o '[[:digit:]]*%')"
                  [ "${sinks#*Active Port:*-speaker}" != "$sinks" ] && echo "VOL_SYM:🔈"
                  [ "${sinks#*Active Port:*-headphone}" != "$sinks" ] && echo "VOL_SYM:🎧"
                  [ "${sinks#*Active Port: headset-output}" != "$sinks" ] && echo "VOL_SYM:🎧[$bt_bat]"
          }
          [ "${event#*Event \'change\' on sink}" != "$event" ] && {
                  ds="Sink #${event#*\#}"
                  vol="${sinks#*$ds}"; vol="${vol%%%*}"; vol="${vol##* }"; echo "VOL:$vol"
          }
  done
}
