#!/bin/sh
sinks="$(pactl list sinks)"
[ "${sinks#*Active Port:*-speaker}" != "$sinks" ] && echo "VOL_SYM:"
[ "${sinks#*Active Port:*-headphone}" != "$sinks" ]  && echo "VOL_SYM:"
vol="${sinks#*availability unknown)}"; vol="${vol%%%*}"; vol="${vol##* }"; echo "VOL:$vol"
pactl subscribe | while read -r event; do
        [ "${event#*client}" != "$event" ] && continue
        sinks="$(pactl list sinks)"
        [ "${event#*\'change\' on card}" != "$event" ] && {
                [ "${sinks#*Active Port:*-speaker}" != "$sinks" ] && echo "VOL_SYM:"
                [ "${sinks#*Active Port:*-headphone}" != "$sinks" ] && echo "VOL_SYM:"
        }
        [ "${event#*Event \'change\' on sink}" != "$event" ] && {
                vol="${sinks#*availability unknown)}"; vol="${vol%%%*}"; vol="${vol##* }"; echo "VOL:$vol"
        }
done
