#!/bin/sh

ps_PLAYERCTL() {
  echo "PLAYERCTL:"
  playerctl -p cmus,%any -i chromium -F metadata -f '[ {{emoji(status)}} {{trunc(title,30)}} ({{trunc(artist, 20)}}) ]' | while read -r data; do
    echo "PLAYERCTL:$data"
  done
}
