#!/bin/sh
while true; do
        cpu_temp="$(sensors)"; cpu_temp="${cpu_temp#*Tdie*+}"
        cpu_temp="${cpu_temp#*Tdie*-}"
        [ "$prev_temp" != "$cpu_temp" ] && \
                prev_temp="$cpu_temp" && echo "TEMP:${cpu_temp%% *}"
        sleep 1m
done
